"""UI copy in English and Norwegian (bokmål)."""

STRINGS = {
    "en": {
        "title": "PDF Metric Extractor",
        "subtitle": "Upload reports, name your metrics — get every value in one table, each with an exact, highlighted source in its PDF.",
        "upload_label": "Upload PDF reports (e.g. annual or quarterly reports)",
        "metrics_label": "Metrics to extract (one per line)",
        "metrics_help": "Name the metrics the way you would ask a colleague — e.g. “Revenue Q2 2025” or “EBITDA margin”.",
        "extract_button": "Extract metrics",
        "settings": "Settings",
        "engine": "Extraction engine",
        "engine_llm": "AI (Model Serving endpoint)",
        "engine_heuristic": "Heuristic (offline, no AI)",
        "endpoint_label": "Serving endpoint name",
        "endpoint_help": "A chat-capable Model Serving endpoint in this workspace. The app's service principal needs CAN QUERY on it.",
        "language": "Language / Språk",
        "results_header": "Results",
        "evidence_header": "Evidence in the document",
        "page_label": "Page",
        "not_found": "Not found",
        "found_not_located": "Value found, but could not be pinned to the page — verify manually.",
        "no_text_warning": "This PDF has little or no extractable text — it may be scanned. OCR is not supported yet; results will be poor.",
        "extracting": "Reading the document and extracting metrics…",
        "locating": "Pinning values to their exact position in the PDF…",
        "llm_error": "Could not query the serving endpoint. Check that the endpoint name is correct and that the app has CAN QUERY permission on it. Falling back to the offline heuristic engine.",
        "download_pdf": "Download annotated PDF",
        "download_csv": "Download results (CSV)",
        "select_metric": "Show evidence for",
        "legend_value": "value",
        "legend_label": "label",
        "legend_context": "context",
        "quote_caption": "Model quote",
        "comment_caption": "Note",
        "confidence": "confidence",
        "period": "Period",
        "no_metrics_warning": "Enter at least one metric to extract.",
        "upload_first": "Upload a PDF to get started.",
        "pdf_error": "Could not read this PDF — the file appears corrupt or password-protected.",
        "stale_settings": "⚠️ Not in the table yet, or extracted with different settings: {reports}. Press the button to (re-)extract.",
        "meta_header": "Report metadata",
        "meta_help": "Company and year are guessed from each file — correct them here; they go into the results table and CSV.",
        "col_company": "Company",
        "col_report": "Report",
        "col_year": "Year",
        "company_label": "Company",
        "year_label": "Year",
        "evidence_pick_fmt": "{report} — {metric}",
        "download_pdf_one": "Download annotated PDF for this report",
        "skipped_file": "Skipped (unreadable PDF):",
        "occurrences_label": "Where this metric appears in the report ({n})",
        "occurrence_extracted": "extracted",
        "occurrence_fmt": "Page {page} · {value}",
        "ambiguity_warning": "This metric is stated with {n} different values in this report — check that the extracted one is the figure you want (a group total, not a segment or an earlier year).",
        "adopt_button": "Use this value instead",
        "adopted_note": "Value replaced by hand from another place in the report.",
        "viewing_other": "Showing another occurrence — the table still holds the extracted value.",
        "pages": "pages",
        "col_metric": "Metric",
        "col_value": "Value",
        "col_unit": "Unit",
        "col_period": "Period",
        "col_page": "Page",
        "col_confidence": "Confidence",
        "col_status": "Status",
        "status_located": "Located",
        "status_found": "Found (not pinned)",
        "status_missing": "Not found",
    },
    "no": {
        "title": "PDF-nøkkeltallsuttrekk",
        "subtitle": "Last opp rapporter og angi nøkkeltall — få alle verdiene i én tabell, hver med nøyaktig, markert kilde i sin PDF.",
        "upload_label": "Last opp PDF-rapporter (f.eks. års- eller kvartalsrapporter)",
        "metrics_label": "Nøkkeltall som skal hentes ut (ett per linje)",
        "metrics_help": "Skriv nøkkeltallene slik du ville spurt en kollega — f.eks. «Driftsinntekter Q2 2025» eller «EBITDA-margin».",
        "extract_button": "Hent ut nøkkeltall",
        "settings": "Innstillinger",
        "engine": "Uttrekksmotor",
        "engine_llm": "KI (Model Serving-endepunkt)",
        "engine_heuristic": "Heuristisk (frakoblet, uten KI)",
        "endpoint_label": "Navn på serving-endepunkt",
        "endpoint_help": "Et chat-endepunkt i dette arbeidsområdet. Appens service principal trenger CAN QUERY på endepunktet.",
        "language": "Language / Språk",
        "results_header": "Resultater",
        "evidence_header": "Dokumentasjon i dokumentet",
        "page_label": "Side",
        "not_found": "Ikke funnet",
        "found_not_located": "Verdien ble funnet, men kunne ikke festes til siden — kontroller manuelt.",
        "no_text_warning": "PDF-en har lite eller ingen maskinlesbar tekst — den kan være skannet. OCR støttes ikke ennå; resultatene blir dårlige.",
        "extracting": "Leser dokumentet og henter ut nøkkeltall …",
        "locating": "Fester verdiene til nøyaktig posisjon i PDF-en …",
        "llm_error": "Fikk ikke kontakt med serving-endepunktet. Sjekk at navnet stemmer og at appen har CAN QUERY-tilgang. Faller tilbake til den frakoblede heuristiske motoren.",
        "download_pdf": "Last ned annotert PDF",
        "download_csv": "Last ned resultater (CSV)",
        "select_metric": "Vis dokumentasjon for",
        "legend_value": "verdi",
        "legend_label": "etikett",
        "legend_context": "kontekst",
        "quote_caption": "Modellens sitat",
        "comment_caption": "Merknad",
        "confidence": "sikkerhet",
        "period": "Periode",
        "no_metrics_warning": "Angi minst ett nøkkeltall.",
        "upload_first": "Last opp en PDF for å komme i gang.",
        "pdf_error": "Kunne ikke lese PDF-en — filen ser ut til å være ødelagt eller passordbeskyttet.",
        "stale_settings": "⚠️ Ikke i tabellen ennå, eller hentet ut med andre innstillinger: {reports}. Trykk på knappen for å hente ut (på nytt).",
        "meta_header": "Rapportmetadata",
        "meta_help": "Selskap og år gjettes fra hver fil — rett dem her; de brukes i resultattabellen og CSV-en.",
        "col_company": "Selskap",
        "col_report": "Rapport",
        "col_year": "År",
        "company_label": "Selskap",
        "year_label": "År",
        "evidence_pick_fmt": "{report} — {metric}",
        "download_pdf_one": "Last ned annotert PDF for denne rapporten",
        "skipped_file": "Hoppet over (uleselig PDF):",
        "occurrences_label": "Hvor nøkkeltallet står i rapporten ({n})",
        "occurrence_extracted": "uthentet",
        "occurrence_fmt": "Side {page} · {value}",
        "ambiguity_warning": "Nøkkeltallet oppgis med {n} ulike verdier i denne rapporten — kontroller at den uthentede er tallet du vil ha (konserntall, ikke et forretningsområde eller et tidligere år).",
        "adopt_button": "Bruk denne verdien i stedet",
        "adopted_note": "Verdien er byttet manuelt til et annet sted i rapporten.",
        "viewing_other": "Viser en annen forekomst — tabellen inneholder fortsatt den uthentede verdien.",
        "pages": "sider",
        "col_metric": "Nøkkeltall",
        "col_value": "Verdi",
        "col_unit": "Enhet",
        "col_period": "Periode",
        "col_page": "Side",
        "col_confidence": "Sikkerhet",
        "col_status": "Status",
        "status_located": "Lokalisert",
        "status_found": "Funnet (ikke festet)",
        "status_missing": "Ikke funnet",
    },
}

DEFAULT_METRICS = {
    "en": "Revenue\nEBITDA\nOperating profit\nProfit before tax\nNet income",
    "no": "Driftsinntekter\nEBITDA\nDriftsresultat\nResultat før skatt\nÅrsresultat",
}
