[theme]
primaryColor = "#E81A3B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F2F2"
textColor = "#333333"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 100
